//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiagnosisOfRetinal
{
    using System;
    using System.Collections.Generic;

    [Serializable]
    public partial class Correlation
    {
        public Correlation()
        {

        }

        public long ID_survey { get; set; }
        public int Num_first_snapshot { get; set; }
        public int Num_second_snapshot { get; set; }
        public double Сoefficient { get; set; }
    
        public virtual Survey Survey { get; set; }
    }
}
