//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiagnosisOfRetinal
{
    using System;
    using System.Collections.Generic;

    [Serializable]
    public partial class Critical_points
    {
        public Critical_points()
        {

        }

        public long ID_survey { get; set; }
        public int Num_first_snapshot { get; set; }
        public int Num_second_snapshot { get; set; }
        public int Count { get; set; }
    
        public virtual Survey Survey { get; set; }
    }
}
