//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiagnosisOfRetinal
{
    using System;
    using System.Collections.Generic;

    [Serializable]
    public partial class EachHole
    {
        public EachHole()
        {

        }

        public long ID_hole { get; set; }
        public long ID_holes { get; set; }
        public double Hole_size { get; set; }
    
        public virtual Hole Hole { get; set; }
    }
}
