//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiagnosisOfRetinal
{
    using System;
    using System.Collections.Generic;

    [Serializable]
    public partial class Folding
    {
        public Folding()
        {

        }

        public long ID_survey { get; set; }
        public int Num_snapshot { get; set; }
        public double Max_amplitude { get; set; }
        public double Min_amplitude { get; set; }
        public double Mean_amplitude { get; set; }
        public int N { get; set; }
        public double Angles { get; set; }
        public Nullable<double> Area_of_membrane { get; set; }
    
        public virtual Survey Survey { get; set; }
    }
}
