//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiagnosisOfRetinal
{
    using System;
    using System.Collections.Generic;

    [Serializable]
    public partial class Fourier_params
    {
        public Fourier_params()
        {

        }

        public long ID_survey { get; set; }
        public int Num_snapshot { get; set; }
        public int High_freq_amount { get; set; }
        public int Middle_freq_amount { get; set; }
        public int Low_freq_amount { get; set; }
        public double High_freq_amp { get; set; }
        public double Middle_freq_amp { get; set; }
        public double Low_freq_amp { get; set; }
        public double High_freq_mean { get; set; }
        public double Middle_freq_mean { get; set; }
        public double Low_freq_mean { get; set; }
    
        public virtual Survey Survey { get; set; }
    }
}
