//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiagnosisOfRetinal
{
    using System;
    using System.Collections.Generic;

    [Serializable]
    public partial class Fovea
    {
        public Fovea()
        {

        }

        public long ID_survey { get; set; }
        public int Num_snapshot { get; set; }
        public double Length { get; set; }
        public double Depth_top { get; set; }
        public double Depth_bot { get; set; }
        public double Coef_symmetry { get; set; }
        public double Coef_normality { get; set; }
    
        public virtual Survey Survey { get; set; }
    }
}
